### ISSUE TITLE
Fix Qt install failure on macOS GitHub Actions

### ISSUE THREAD

**Issue by dalboris** [vgc/vgc#494]
See: https://github.com/jurplel/install-qt-action/issues/85

Note that it seems that I have explicitly set setup-python to false because otherwise the wrong Qt version was installed, see:

https://github.com/vgc/vgc/pull/464/commits/8294a2306c643d2742c33b1f0ea76a8c1a2472ea

**Comment by dalboris** [comment]
Ok, installation of Qt seems to work when setting setup-python to true, but then this messes up the version of Python used for the rest of the build. I manually want Python 3.7, and use a specific action for this:

```
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        architecture: 'x64'
```

But then when this action runs :

```
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{env.QT_VERSION}}
        setup-python: true
```

I get this Python version (see https://github.com/vgc/vgc/pull/495/checks?check_run_id=1972770710):

```
-- [Python]
-- Found PythonInterp: /Users/runner/hostedtoolcache/Python/3.9.1/x64/bin/python3 (found suitable version "3.9.1", minimum required is "3.6") 
-- Found PythonLibs: /Users/runner/hostedtoolcache/Python/3.9.1/x64/lib/libpython3.9.dylib (found suitable version "3.9.1", minimum required is "3.6") 
-- Version: 3.9.1
CMake Deprecation Warning at third/googletest/CMakeLists.txt:4 (cmake_minimum_required):
-- PYTHON_PREFIX: /Users/runner/hostedtoolcache/Python/3.9.1/x64
  Compatibility with CMake < 2.8.12 will be removed from a future version of
-- PYTHON_EXEC_PREFIX: /Users/runner/hostedtoolcache/Python/3.9.1/x64
  CMake.
-- PYTHON_HOME: /Users/runner/hostedtoolcache/Python/3.9.1/x64
```

which causes deployment to fail:

```
Scanning dependencies of target deploy
Traceback (most recent call last):
  File "/Users/runner/work/vgc/vgc/tools/macos/deploy.py", line 58, in <module>
    import dmgbuild
ModuleNotFoundError: No module named 'dmgbuild'
make[3]: *** [CMakeFiles/deploy] Error 1
make[2]: *** [CMakeFiles/deploy.dir/all] Error 2
make[1]: *** [CMakeFiles/deploy.dir/rule] Error 2
make: *** [deploy] Error 2
Error: Process completed with exit code 2.
```

Indeed, dmgbuild was installed with the PIP of Python 3.7 (see the order in the Yaml file below) and thus can't be found by the Python 3.9 set by the install-qt-action:

```
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        architecture: 'x64'

    - name: Install most dependencies
      shell: bash
      working-directory: ${{runner.workspace}}
      run: |
        brew install freetype
        brew install harfbuzz
        pip3 install dmgbuild

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{env.QT_VERSION}}
        setup-python: true
```

Let's try to reorder things and see if it works. First install Qt with setup-python: true. Then manually setup python to the version I desire. Then install all other dependencies and build.
